### ISSUE TITLE
Intallation error chmod +x gradlew && ./gradlew build 

### ISSUE THREAD

**Issue by ritukajaiswal** [emufog/emufog#21]
Hi,
I tried running the command chmod +x gradlew && ./gradlew build --stacktrace and found the euro as 
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.1'.
* Exception is:
java.lang.IllegalArgumentException: Could not determine java version from '11.0.1'
Please suggest a solution

**Comment by ritukajaiswal** [comment]
The issue was with java version as MAC doesn't take correct version from /Library

**Comment by unly** [comment]
Yes this issue is related to the version of the jdk and its installation. Glad you solved it that fast :smile:
