### ISSUE TITLE
error while running command java -jar build/libs/emufog-1.0-fat.jar

### ISSUE THREAD

**Issue by ritukajaiswal** [emufog/emufog#23]
Hi, 
I may be doing some fundamental mistake but I need help 
Ritukas-MacBook-Pro:emufog rituka$ java -jar build/libs/emufog-1.0-fat.jar
##############################################################
Welcome to EmuFog
##############################################################
Closing EmuFog
Exception in thread "main" java.lang.IllegalArgumentException: The given file path is not initialized.
	at emufog.settings.SettingsReader.read(SettingsReader.java:51)
	at emufog.launcher.Emufog.main(Emufog.java:72)

**Comment by unly** [comment]
Hi @ritu2012 I have to admit I did not spend enough time on logging... The problem is that the it can't find             a settings file. As you probably have not specified any this is the intended behavior. The wiki https://github.com/emufog/emufog/wiki gives you some documentation on settings and [how to start it](https://github.com/emufog/emufog/wiki#launch-emufog).

**Comment by ritu2012** [comment]
Hey, thanks. I was looking for a full guide to install Emufog step by step and run. Will let you know the status.

**Comment by ritukajaiswal** [comment]
Hey thanks. will let you know the status.

**Comment by ritukajaiswal** [comment]
Hey, I feel if get a document which tells step by step of what commands to run and prerequisites like installing Maxinet etc, then it would be of great help. I need to understand the framework and then I can run more meaningfully.

**Comment by ritukajaiswal** [comment]
Hi, How do I generate topology.brite file? How do I download BRITE ? java -jar emufog.jar -s settings.json -t brite -f topology.brite -o out.py this command needs the file.

**Comment by unly** [comment]
> Hey, I feel if get a document which tells step by step of what commands to run and prerequisites like installing Maxinet etc, then it would be of great help. I need to understand the framework and then I can run more meaningfully.

Valid point. So far we mostly checked the Maxinet page to get instructions and documentation. Maybe a end-to-end guide would be useful.

> Hi, How do I generate topology.brite file? How do I download BRITE ? java -jar emufog.jar -s settings.json -t brite -f topology.brite -o out.py this command needs the file.

BRITE is a network topology generator by the univesity of Boston. https://www.cs.bu.edu/brite
Unfortunately the last time I checked the download link was down but I hosted the original source code with minor changes for Java 8 on GitHub https://github.com/unly/brite. The website gives you information about the network models available and the parameters.

**Comment by ritukajaiswal** [comment]
Great, Thanks :)

**Comment by ritukajaiswal** [comment]
Hey, I have some questions? Is Emufog Mac compatible ? 
I tried installing Maxinet by running command ./installer.sh. Got these errors 

E: Couldn't find package screen
Reading Package Lists... Done
Building Dependency Tree... Done
E: Couldn't find package ansible
grep: /etc/ansible/hosts: No such file or directory
tee: /etc/ansible/hosts: No such file or directory
localhost ansible_connection=local
Cloning into 'containernet'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 9814 (delta 12), reused 16 (delta 6), pack-reused 9786
Receiving objects: 100% (9814/9814), 3.04 MiB | 978.00 KiB/s, done.
Resolving deltas: 100% (6472/6472), done.
sudo: ansible-playbook: command not found
./installer.sh: line 130: wget: command not found
tar (child): metis-5.1.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: metis-5.1.0.tar.gz: No such file or directory
./installer.sh: line 133: cd: metis-5.1.0: No such file or directory
make: *** No rule to make target `config'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
Reading Package Lists... Done
Building Dependency Tree... Done
E: Couldn't find package python-pip
The directory '/Users/rituka/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/rituka/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: Pyro4 in /anaconda3/lib/python3.7/site-packages (4.74)
Requirement already satisfied: serpent>=1.27 in /anaconda3/lib/python3.7/site-packages (from Pyro4) (1.27)
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Cloning into 'MaxiNet'...
remote: Enumerating objects: 1192, done.
remote: Total 1192 (delta 0), reused 0 (delta 0), pack-reused 1192
Receiving objects: 100% (1192/1192), 327.50 KiB | 512.00 KiB/s, done.
Resolving deltas: 100% (777/777), done.
Note: checking out 'v1.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at fd493f8 Release version 1.2
python2 setup.py install
make: python2: No such file or directory
make: *** [install] Error 1

**Comment by ritukajaiswal** [comment]
Hey, 
Do u have a video of how you installed emu fog on your system and run a sample application ? I somehow can not connect what fog applications can be run on this?

**Comment by ritukajaiswal** [comment]
Hey, does it require python 2.7 to run?  
Can I change it to 3.7 as I am getting the following error 
HEAD is now at fd493f8 Release version 1.2
python2 setup.py install
make: python2: No such file or directory

**Comment by unly** [comment]
Hi @ritu2012,
EmuFog just creates MaxiNet experiments for you. The output is a python file ready to run with MaxiNet. As EmuFog is written in Java it runs on any platform that supports Java. MacOS does support it. We developed it in Java 8 and I'm personally not sure about newer versions of Java and If you want to make sure use Java 8.
To install MaxiNet follow [the install file](https://github.com/MaxiNet/MaxiNet/blob/master/INSTALL.txt). I personally don't know about the python 2.7 or 3.7 issue of yours. If you're having problems with MaxiNet I would recommend to get in touch with someone from the project.

**Comment by ritukajaiswal** [comment]
Thanks. 






Get Outlook for Android







On Mon, Dec 3, 2018 at 4:14 PM +0100, "Leon Graser" <notifications@github.com> wrote:












Hi @ritu2012,

EmuFog just creates MaxiNet experiments for you. The output is a python file ready to run with MaxiNet. As EmuFog is written in Java it runs on any platform that supports Java. MacOS does support it. We developed it in Java 8 and I'm personally not sure about newer versions of Java and If you want to make sure use Java 8.

To install MaxiNet follow the install file. I personally don't know about the python 2.7 or 3.7 issue of yours. If you're having problems with MaxiNet I would recommend to get in touch with someone from the project.

**Comment by Znbne** [comment]
Hello unly,
Could you please guide me on how to run emufog in netbeans or other java IDE? How can I run it with a CAIDA topology?

Thank you for your time.

**Comment by unly** [comment]
Hi @Znbne the arguments to emufog don't change if you run it from the IDE. You can find them here https://github.com/emufog/emufog#execute-emufog. I don't know about NetBeans but for Intellij IDEA you can create run configurations with this guide https://www.jetbrains.com/help/idea/run-debug-configuration.html.

Regarding the CAIDA topology you have to use the respective `*.links`, `*.nodes.as` and the `*.nodes.geo` from your dataset and pass them to emufog with the `-f` flag. It supports multiple files. I hope this helps.

**Comment by Znbne** [comment]
Thank you very much. your guidance helps me so much.
    On Tuesday, October 27, 2020, 09:03:35 PM GMT+3:30, unly <notifications@github.com> wrote:  
 
 


Hi @Znbne the arguments to emufog don't change if you run it from the IDE. You can find them here https://github.com/emufog/emufog#execute-emufog. I don't know about NetBeans but for Intellij IDEA you can create run configurations with this guide https://www.jetbrains.com/help/idea/run-debug-configuration.html.

Regarding the CAIDA topology you have to use the respective *.links, *.nodes.as and the *.nodes.geo from your dataset and pass them to emufog with the -f flag. It supports multiple files. I hope this helps.

**Comment by Znbne** [comment]
Hi unly,
I tried to drive a topology from Caida files with EmuFog, but because the files are too large (4, 1.5, and 3 G) Windows CMD arises heap error. I tried to assign more memory using "org.gradle.jvmargs=-Xmx4608m" but it is not recognized as an argument with Emufog.
Could you please guide me in this regard. 
Although the Caida files in the test folder are too small for my experiments, may I know from where they are provided?  
Is there any command option to run EmuFog with larger memory in Windows?

**Comment by unly** [comment]
Hi @Znbne you can adjust the memory of the JVM using the jvm arguments as described here https://docs.gradle.org/current/userguide/build_environment.html#sec:configuring_jvm_memory. I don't recall the exact syntax but it works to increase the default memory limit. To ease the work with big files we often extracted a subset of the autonomous systems from the files to analyze just the important data. But it should also work with 4gb file sizes. I did it too a while back.

**Comment by Znbne** [comment]
Thank you unly. I try the link completely.

**Comment by Znbne** [comment]
Hello unly,
Thanks to your suggestions and preprocessing the input files, I managed to reach my intended result and run Emufog correctly.
I have a few challenges regarding the output files that I would appreciate if you can help me overcoming them.

I need to feed the output of Emufog to another program which entails the followings:
1. I need to know the position (coordination) of the output file of Emufog. Is there any way to get this? The input files contain these information however in the output file they are removed and there is not any mapping between the input and output files to infer these info.
2. There various kind of nodes in the output file such as switch, fog node, host (nodes with s, h, r, c prefixes). Is there any guidance on what kind of nodes (router, switch, edge node, fog ,...) are them and what are the differences between them.

**Comment by Znbne** [comment]
Hi unly,
I need to know what are the edge routers and which ones are the backbone routers.
There are various kinds of nodes in the output file such as switch, fog node, host (nodes with s, h, r, c prefixes). Is there any guidance on what kind of nodes (router, switch, edge node, fog ,...) are these and what are the differences between them.

**Comment by unly** [comment]
Nodes starting with an `s` are switches and part of the backbone. Nodes starting with an `h` are hosts. Consider them the edge devices. And there are nodes with `r`. Those are routers and part of the edge of the network. Be aware that not all of them run as a fog node. Some have a docker container associated some not.

**Comment by Znbne** [comment]
Thank you. So only the nodes starting with 's' are the backbone routers and the remaining routers are edge ones. Am I right?

**Comment by unly** [comment]
yes
